version: '3'

services:
  frontend:
    image: rapydo/frontend
    command: ./boot
    hostname: frontend
    # TO FIX: fix all mounts!!
    working_dir: /data/submodules/frontend
    environment:
      ACTIVATE: 1  # fixed, because it is enabled by frontend.framework variable
      APP_MODE: debug
    volumes:
      # Main dir. It has to be the root directory, to make links work
      - ${VANILLA_DIR}:/data
      # Vanilla code
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}:/temporaryfix
      # SHARED WITH PROXY:
      - ${SUBMODULE_DIR}/frontend/js/angular:/data/submodules/frontend/felask/static/app/commons
      - ${SUBMODULE_DIR}/frontend/css:/data/submodules/frontend/felask/static/css/base
      - ${SUBMODULE_DIR}/frontend/fonts:/data/submodules/frontend/felask/static/fonts
      - ${SUBMODULE_DIR}/frontend/templates:/data/submodules/frontend/felask/static/app/templates/common
      # js/css libraries installed via bower
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/bower_components:/data/submodules/frontend/felask/static/bower
      # js/css custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/js:/data/submodules/frontend/felask/static/app/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/templates:/data/submodules/frontend/felask/static/app/templates/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/css:/data/submodules/frontend/felask/static/css/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/assets:/data/submodules/frontend/felask/static/assets

  ###############################
  # Make automatic to install libraries
  bower:
    image: pdonorio/jsdev
    working_dir: /confs
    volumes:
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}:/libs
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/package.json:/confs/bower.json

  ###############################
  proxy:
    volumes:
      # SHARED WITH FRONTEND:
      - ${SUBMODULE_DIR}/frontend/js/angular:/data/submodules/frontend/felask/static/app/commons
      - ${SUBMODULE_DIR}/frontend/css:/data/submodules/frontend/felask/static/css/base
      - ${SUBMODULE_DIR}/frontend/fonts:/data/submodules/frontend/felask/static/fonts
      - ${SUBMODULE_DIR}/frontend/templates:/data/submodules/frontend/felask/static/app/templates/common
      # js/css libraries installed via bower
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/bower_components:/data/submodules/frontend/felask/static/bower
      # Custom css/js
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/js:/data/submodules/frontend/felask/static/app/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/templates:/data/submodules/frontend/felask/static/app/templates/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/css:/data/submodules/frontend/felask/static/css/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/assets:/data/submodules/frontend/felask/static/assets
