
version: '3'

services:

  vanilla-formatter:
    image: unibeautify/black:latest
    command: -S .
    volumes:
      - ${SUBMODULE_DIR}/rapydo-confs/confs/formatter.toml:/workdir/pyproject.toml
      - ${PROJECT_DIR}/backend/${BLACK_FOLDER}:/workdir/${BLACK_FOLDER}
    working_dir: /workdir

  submodules-formatter:
    image: unibeautify/black:latest
    command: -S .
    volumes:
      - ${SUBMODULE_DIR}/rapydo-confs/confs/formatter.toml:/workdir/pyproject.toml
      - ${SUBMODULE_DIR}/${BLACK_SUBMODULE}/${BLACK_FOLDER}:/workdir/${BLACK_FOLDER}
    working_dir: /workdir
