version: '3'

services:
  frontend:
    # image: rapydo/frontend
    build:
      context: ${SUBMODULE_DIR}/build-templates/frontend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    image: rapydo/frontend:${RAPYDO_VERSION}
    # command: sleep infinity
    hostname: frontend
    # working_dir: /rapydo/
    environment:
      MODULE_PATH: /modules
      PROJECT_TITLE: ${PROJECT_TITLE}
    volumes:
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}:/app
      - ${SUBMODULE_DIR}/frontend/:/rapydo
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/frontend:/modules

  ###############################
  proxy:
    volumes:
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/frontend:/modules
