version: '3'

services:
  frontend:
    # image: rapydo/frontend
    build:
      context: ${SUBMODULE_DIR}/build-templates/frontend
      args:
        RAPYDO_VERSION: ${RAPYDO_VERSION}
    image: rapydo/frontend:${RAPYDO_VERSION}
    # command: sleep infinity
    hostname: frontend
    working_dir: /app/frontend/
    environment:
      MODULE_PATH: /modules
    volumes:
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}:/app
      - ${SUBMODULE_DIR}/frontend/:/rapydo
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/frontend:/modules

  ###############################
  proxy:
    volumes:
      # SHARED WITH FRONTEND:
      - ${SUBMODULE_DIR}/frontend/js/angular:/data/submodules/frontend/felask/static/app/commons
      - ${SUBMODULE_DIR}/frontend/css:/data/submodules/frontend/felask/static/css/base
      - ${SUBMODULE_DIR}/frontend/fonts:/data/submodules/frontend/felask/static/fonts
      - ${SUBMODULE_DIR}/frontend/templates:/data/submodules/frontend/felask/static/app/templates/common
      # js/css libraries installed via bower
      - ${VANILLA_DIR}/data/${COMPOSE_PROJECT_NAME}/bower_components:/data/submodules/frontend/felask/static/bower
      # Custom css/js
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/js:/data/submodules/frontend/felask/static/app/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/templates:/data/submodules/frontend/felask/static/app/templates/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/css:/data/submodules/frontend/felask/static/css/custom
      - ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/frontend/assets:/data/submodules/frontend/felask/static/assets
